global:
  scrape_interval: 15s # Tần suất thu thập dữ liệu mặc định

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"] # Cấu hình để Prometheus tự theo dõi chính nó