

services:
  postgres:
    image: pgvector/pgvector:pg18-trixie
    container_name: nutrition_postgres
    restart: unless-stopped
    shm_size: '3g'  # Cấp 3GB RAM chia sẻ cho Container (đủ cho maintenance_work_mem = 2GB)
    ports:
      - "5432:5432"
    env_file:
      - ../.env
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_HOST_AUTH_METHOD=${PG_HOST}

    # Ép PostgreSQL khởi chạy và đọc duy nhất file postgresql.conf tập trung
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db_postgres/init_vector_db.sql:/docker-entrypoint-initdb.d/01_init_vector_db.sql:ro
      # Chỉ mount duy nhất 1 file cấu hình này
      - ./db_postgres/postgresql.conf:/etc/postgresql/postgresql.conf:ro

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-nutrition_ai}"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - nutrition_net

volumes:
  pg_data:

networks:
  nutrition_net:
    driver: bridge