

services:
  postgres:
    image: pgvector/pgvector:pg18-trixie
    container_name: nutrition_postgres
    restart: unless-stopped
    shm_size: '3g'
    ports:
      - "5432:5432"
    env_file:
      - ../.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
    
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    
    volumes:
      # ĐÃ SỬA: Mount vào /var/lib/postgresql thay vì /var/lib/postgresql/data
      - pg_data:/var/lib/postgresql
      - ./db_postgres/init_vector_db.sql:/docker-entrypoint-initdb.d/01_init_vector_db.sql:ro
      - ./db_postgres/postgresql.conf:/etc/postgresql/postgresql.conf:ro

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-nutrition_ai}"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - nutrition_net

volumes:
  pg_data:

networks:
  nutrition_net:
    driver: bridge