"""init_nutrition_ai_tables

Revision ID: 12534fffdfa5
Revises: 
Create Date: 2026-10-09 15:13:45.495578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by other tools.
revision: Union[str, None] = '12534fffdfa5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calories', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.alter_column('calories', 'User_ID',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('calories', 'Gender',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('calories', 'Age',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('calories', 'Height',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('calories', 'Weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('calories', 'Duration',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('calories', 'Heart_Rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('calories', 'Body_Temp',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('calories', 'Calories',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_index(op.f('ix_raw_calories_User_ID'), 'calories', ['User_ID'], unique=False, schema='raw')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_calories_User_ID'), table_name='calories', schema='raw')
    op.alter_column('calories', 'Calories',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('calories', 'Body_Temp',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('calories', 'Heart_Rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('calories', 'Duration',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('calories', 'Weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('calories', 'Height',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('calories', 'Age',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('calories', 'Gender',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('calories', 'User_ID',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_column('calories', 'id')
    # ### end Alembic commands ###