# Cấu hình bộ nhớ cho pgvector và PostgreSQL
maintenance_work_mem = 5GB
shared_buffers = 512MB
work_mem = 64MB

# Cho phép kết nối từ bên ngoài
listen_addresses = '*'

# Cấu hình bảo mật cho PostgresML
