database:
  schema_name: "nutrition_ai"
  table_name: "calorie_logs"
  # Không cần connection string/source nữa vì BasePostgresExtractor đã gọi get_connection() tự động

feature_store:
  file_path: "Artifacts/choose_features/ml_calories/calories_features.csv"
  dvc_tracked: true

target_column:
  name: "Calories"
  type: "float"

INDEX:
  name: "User_ID"



data_split:
  train_ratio: 0.8
  test_ratio: 0.1
  validation_ratio: 0.1

output:
  data_version: "v1.0.0"

schema:
  json_schema_file: "config/pipelines/ml_calories/calories_data_schema.json"