features:
- LightActiveDistance
- FairlyActiveMinutes
- SedentaryMinutes
- Calories_mean_fitabase_data_3_12_16_4_11_16_hourlyCalories_merged
- AverageIntensity_get_skew_fitabase_data_3_12_16_4_11_16_hourlyIntensities_merged
- StepTotal_median_fitabase_data_3_12_16_4_11_16_hourlySteps_merged
- StepTotal_q3_fitabase_data_3_12_16_4_11_16_hourlySteps_merged
- StepTotal_get_kurt_fitabase_data_3_12_16_4_11_16_hourlySteps_merged
- Calories_median_fitabase_data_3_12_16_4_11_16_minuteCaloriesNarrow_merged
- Calories_q3_fitabase_data_3_12_16_4_11_16_minuteCaloriesNarrow_merged
- Intensity_max_fitabase_data_3_12_16_4_11_16_minuteIntensitiesNarrow_merged
- METs_min_fitabase_data_3_12_16_4_11_16_minuteMETsNarrow_merged
- METs_median_fitabase_data_3_12_16_4_11_16_minuteMETsNarrow_merged
- METs_q1_fitabase_data_3_12_16_4_11_16_minuteMETsNarrow_merged
- METs_get_skew_fitabase_data_3_12_16_4_11_16_minuteMETsNarrow_merged
- Steps_get_skew_fitabase_data_3_12_16_4_11_16_minuteStepsNarrow_merged
metadata:
  description: Generated automatically after collinearity removal.
  num_features: 16
target: Calories
