fitness_tracker_dataset:
  db_schema: raw
  table_name: fitness_tracker_dataset
  columns:
    user_id:
      type: integer
      nullable: false
      description: ''
    date:
      type: categorical
      nullable: false
      description: ''
    steps:
      type: integer
      nullable: false
      description: ''
    calories_burned:
      type: float
      nullable: false
      description: ''
    distance_km:
      type: float
      nullable: false
      description: ''
    active_minutes:
      type: integer
      nullable: false
      description: ''
    sleep_hours:
      type: float
      nullable: false
      description: ''
    heart_rate_avg:
      type: integer
      nullable: false
      description: ''
    workout_type:
      type: categorical
      nullable: true
      description: ''
    weather_conditions:
      type: categorical
      nullable: false
      description: ''
    location:
      type: categorical
      nullable: false
      description: ''
    mood:
      type: categorical
      nullable: false
      description: ''
  numerical_columns:
  - user_id
  - steps
  - calories_burned
  - distance_km
  - active_minutes
  - sleep_hours
  - heart_rate_avg
  categorical_columns:
  - date
  - workout_type
  - weather_conditions
  - location
  - mood
