# alembic.ini
[alembic]
script_location = alembic
# Để trống URL, chúng ta sẽ nạp động từ connection.py
sqlalchemy.url = 
output_encoding = utf-8

[post_write_hooks]
# Bạn có thể thêm cấu hình Black/Ruff formatter vào đây nếu muốn